//! Interactive configuration setup command

use anyhow::Result;
use std::io::{self, Write};

/// Run the interactive configuration setup
pub async fn run() -> Result<()> {
    println!("StellarStack Daemon Configuration");
    println!("==================================\n");

    // Panel URL
    print!("Panel URL [http://localhost:3001]: ");
    io::stdout().flush()?;
    let mut panel_url = String::new();
    io::stdin().read_line(&mut panel_url)?;
    let panel_url = panel_url.trim();
    let panel_url = if panel_url.is_empty() {
        "http://localhost:3001"
    } else {
        panel_url
    };

    // Token ID
    print!("Node Token ID: ");
    io::stdout().flush()?;
    let mut token_id = String::new();
    io::stdin().read_line(&mut token_id)?;
    let token_id = token_id.trim();

    // Token
    print!("Node Token: ");
    io::stdout().flush()?;
    let mut token = String::new();
    io::stdin().read_line(&mut token)?;
    let token = token.trim();

    // API Port
    print!("API Port [8080]: ");
    io::stdout().flush()?;
    let mut api_port = String::new();
    io::stdin().read_line(&mut api_port)?;
    let api_port = api_port.trim();
    let api_port: u16 = if api_port.is_empty() {
        8080
    } else {
        api_port.parse().unwrap_or(8080)
    };

    // SFTP Port
    print!("SFTP Port [2022]: ");
    io::stdout().flush()?;
    let mut sftp_port = String::new();
    io::stdin().read_line(&mut sftp_port)?;
    let sftp_port = sftp_port.trim();
    let sftp_port: u16 = if sftp_port.is_empty() {
        2022
    } else {
        sftp_port.parse().unwrap_or(2022)
    };

    // Generate config
    let config = format!(
        r#"# StellarStack Daemon Configuration
# Generated by stellar-daemon configure

debug: false

api:
  host: "0.0.0.0"
  port: {}
  ssl:
    enabled: false
    cert: ""
    key: ""
  upload_limit: 100
  trusted_proxies: []

system:
  root_directory: "/var/lib/stellar"
  data_directory: "/var/lib/stellar/volumes"
  backup_directory: "/var/lib/stellar/backups"
  archive_directory: "/var/lib/stellar/archives"
  tmp_directory: "/tmp/stellar"
  log_directory: "/var/log/stellar"
  username: "stellar"
  timezone: "UTC"
  disk_check_interval: 60
  user:
    uid: 1000
    gid: 1000

docker:
  socket: "/var/run/docker.sock"
  network:
    name: "stellar"
    interface: "172.18.0.1"
    driver: "bridge"
    is_internal: false
  tmpfs_size: 100
  container_pid_limit: 512
  installer_limits:
    memory: 1024
    cpu: 100
  overhead:
    default: 0
    override: {{}}

remote:
  url: "{}"
  token_id: "{}"
  token: "{}"
  timeout: 30
  boot_servers_per_page: 50

sftp:
  enabled: true
  bind_address: "0.0.0.0"
  bind_port: {}
  read_only: false
"#,
        api_port, panel_url, token_id, token, sftp_port
    );

    // Write config file
    std::fs::write("config.yml", &config)?;
    println!("\nConfiguration written to config.yml");

    Ok(())
}
